steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-central1-docker.pkg.dev/supple-gearbox-447219-d0/lalitha-100979071/assignment2:${COMMIT_SHA}', 
           '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'us-central1-docker.pkg.dev/supple-gearbox-447219-d0/lalitha-100979071/assignment2:${COMMIT_SHA}']

images:
  - 'us-central1-docker.pkg.dev/supple-gearbox-447219-d0/lalitha-100979071/assignment2:${COMMIT_SHA}'

options:
    defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
